// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkodadzhkwqhgwyzyiez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrb2RhZHpoa3dxaGd3eXp5aWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTE4NjgsImV4cCI6MjA2NzIyNzg2OH0.lKCOtr_FETqN1eluY4j-nho9mSW0e6SKrW4uXOFcXdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});